### ISSUE TITLE
arkDesktop 1.3.0 doesn't start

### ISSUE THREAD

**Issue by virgolus** [ArkEcosystem/ark-desktop#184]
I've download version 1.3.0 for OSX.
After application launch, I've a window with this error:

**A JavaScript error occurred in the main process**

Uncaught Exception:
Error: dlopen(/private/var/folders/dp/mmg1g0ys4mlf_0vyvghj7wbr0000gn/T/AppTranslocation/5A0EFD6C-D9EA-45A8-B164-2DB4BE786171/d/ArkClient.app/Contents/Resources/app/node_modules/node-hid/build/Release/HID.node, 1): no suitable image found.  Did find:
	/private/var/folders/dp/mmg1g0ys4mlf_0vyvghj7wbr0000gn/T/AppTranslocation/5A0EFD6C-D9EA-45A8-B164-2DB4BE786171/d/ArkClient.app/Contents/Resources/app/node_modules/node-hid/build/Release/HID.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/private/var/folders/dp/mmg1g0ys4mlf_0vyvghj7wbr0000gn/T/AppTranslocation/5A0EFD6C-D9EA-45A8-B164-2DB4BE786171/d/ArkClient.app/Contents/Resources/app/node_modules/node-hid/build/Release/HID.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/var/folders/dp/mmg1g0ys4mlf_0vyvghj7wbr0000gn/T/AppTranslocation/5A0EFD6C-D9EA-45A8-B164-2DB4BE786171/d/ArkClient.app/Contents/Resources/app/node_modules/node-hid/nodehid.js:9:15)
    at Object.<anonymous> (/private/var/folders/dp/mmg1g0ys4mlf_0vyvghj7wbr0000gn/T/AppTranslocation/5A0EFD6C-D9EA-45A8-B164-2DB4BE786171/d/ArkClient.app/Contents/Resources/app/node_modules/node-hid/nodehid.js:109:3)

The previously release (1.2.2) work.

Osx version: Sierra, 10.12.6

**Comment by fix** [comment]
yes the compilation of native HID went wrong somehow, rebuilding the macosx version

**Comment by fix** [comment]
can you try the new build now, it should be fixed by now -> https://github.com/ArkEcosystem/ark-desktop/releases/download/1.3.0/ArkClient-Macos-1.3.0.dmg

**Comment by virgolus** [comment]
The new build works fine.
Thank you
